import { NextResponse } from "next/server";
import prisma from "@/lib/prisma";
import { auth } from "@/lib/auth";
import { calculateSystemSHU } from "@/lib/services/shu-calculator";
import { isAutoGeneratedPiutang } from "@/lib/laporan-helpers";

// GET /api/member-portal/summary - Get member's complete summary
export async function GET() {
    try {
        const session = await auth();
        if (!session?.user || !session.user.memberId) {
            return NextResponse.json({ message: "Unauthorized" }, { status: 401 });
        }

        const memberId = session.user.memberId;

        // Get member info
        const member = await prisma.member.findUnique({
            where: { id: memberId },
            include: {
                branch: true,
            },
        });

        if (!member) {
            return NextResponse.json({ message: "Member not found" }, { status: 404 });
        }

        // Get savings accounts with balances
        const savingsAccounts = await prisma.savingsAccount.findMany({
            where: { memberId, status: "active" },
            include: {
                product: {
                    select: {
                        id: true,
                        code: true,
                        name: true,
                        type: true,
                        targetAmount: true,
                        linkedBankName: true,
                    },
                },
                transactions: {
                    select: {
                        id: true,
                        type: true,
                        amount: true,
                        notes: true,
                        transactionDate: true,
                    },
                    orderBy: { transactionDate: "asc" },
                },
            },
        });

        const totalSavings = savingsAccounts.reduce(
            (sum, acc) => sum + Number(acc.balance),
            0
        );

        // Get active loans
        const loans = await prisma.loan.findMany({
            where: { memberId },
            select: {
                id: true,
                loanNo: true,
                principalAmount: true,
                principalPaid: true,
                interestPaid: true,
                principalOutstanding: true,
                interestOutstanding: true,
                monthlyInstallment: true,
                tenorMonths: true,
                status: true,
                disbursementDate: true,
                firstDueDate: true,
                lastDueDate: true,
                paidOffDate: true,
            },
        });

        const activeLoans = loans.filter((l) => l.status === "active");
        const totalOutstanding = activeLoans.reduce(
            (sum, l) => sum + Number(l.principalOutstanding) + Number(l.interestOutstanding),
            0
        );

        // Get unit transactions summary — fetch extra to allow for dedup filtering
        const unitTransactionsRaw = await prisma.unitTransaction.findMany({
            where: { memberId },
            orderBy: { transactionDate: "desc" },
            take: 20,
            select: {
                id: true, transactionNo: true, unitType: true, description: true,
                amount: true, transactionDate: true, isPaid: true, paidDate: true,
                status: true, paymentMethod: true, notes: true,
            },
        });

        // Dedup: exclude auto-generated salary_cut piutang (StoreSale already represents them)
        const unitTransactions = unitTransactionsRaw.filter(t => {
            if (t.paymentMethod === "salary_cut" && isAutoGeneratedPiutang(t.notes)) {
                return false;
            }
            return true;
        });

        // Fetch StoreSale for dashboard history (filter voided in JS — Prisma JSON filter
        // excludes rows where metadata is null, which is most sales)
        const storeSaleTxsRaw = await prisma.storeSale.findMany({
            where: { memberId },
            orderBy: { createdAt: "desc" },
            take: 15,
            select: {
                id: true, saleNo: true, unitType: true, totalAmount: true,
                createdAt: true, paymentMethod: true, metadata: true,
                items: { select: { product: { select: { name: true } }, quantity: true } },
            },
        });
        const storeSaleTxs = storeSaleTxsRaw.filter(s => !(s.metadata?.isVoided === true));

        const paymentLabels: Record<string, string> = { cash: "Tunai", qris: "QRIS", salary_cut: "Potong Gaji" };

        // Merge UnitTransaction + StoreSale into unified recent list
        const mergedRecent = [
            ...unitTransactions.map(t => ({
                id: t.id,
                transactionNo: t.transactionNo,
                unitType: t.unitType,
                description: t.description,
                amount: Number(t.amount),
                transactionDate: t.transactionDate,
                isPaid: t.isPaid,
                status: t.status,
                paymentMethod: t.paymentMethod,
                source: 'unit' as const,
            })),
            ...storeSaleTxs.map(s => {
                const itemDesc = s.items.map(i => `${i.product?.name || "[Produk Dihapus]"} x${i.quantity}`).join(', ');
                return {
                    id: s.id + 100000, // offset to avoid ID clash in frontend keys
                    transactionNo: s.saleNo,
                    unitType: s.unitType || 'toko',
                    description: itemDesc || 'Belanja Toko',
                    amount: Number(s.totalAmount),
                    transactionDate: s.createdAt,
                    isPaid: s.paymentMethod !== "salary_cut",
                    status: 'completed',
                    paymentMethod: s.paymentMethod,
                    source: 'store' as const,
                };
            }),
        ].sort((a, b) => new Date(b.transactionDate).getTime() - new Date(a.transactionDate).getTime()).slice(0, 10);

        // Stats: combine both tables — exclude auto-generated salary_cut from UnitTransaction stats
        // (StoreSale already represents those transactions)
        const unitStats = await prisma.unitTransaction.groupBy({
            by: ["unitType"],
            where: {
                memberId,
                status: { not: "voided" },
                NOT: {
                    paymentMethod: "salary_cut",
                    notes: { startsWith: "Auto-generated dari penjualan kasir" },
                },
            },
            _sum: { amount: true },
            _count: { id: true },
        });

        // FIX: Use findMany to filter voided sales
        const storeStatsRaw = await prisma.storeSale.findMany({
            where: { memberId },
            select: { unitType: true, totalAmount: true, metadata: true },
        });

        // Merge stats by unitType
        const statsMap = new Map<string, { totalAmount: number; count: number }>();
        for (const s of unitStats) {
            const key = s.unitType;
            const exist = statsMap.get(key) || { totalAmount: 0, count: 0 };
            exist.totalAmount += Number(s._sum.amount || 0);
            exist.count += s._count.id;
            statsMap.set(key, exist);
        }
        for (const s of storeStatsRaw) {
            // Skip voided
            if (s.metadata) {
                const meta = typeof s.metadata === "object" ? s.metadata : JSON.parse(s.metadata as string);
                if ((meta as any).isVoided) continue;
            }
            const key = s.unitType;
            const exist = statsMap.get(key) || { totalAmount: 0, count: 0 };
            exist.totalAmount += Number(s.totalAmount || 0);
            exist.count += 1;
            statsMap.set(key, exist);
        }
        const mergedStats = Array.from(statsMap.entries()).map(([unitType, v]) => ({ unitType, ...v }));

        // Unpaid piutang: exclude auto-generated salary_cut (StoreSale handles those)
        const unpaidUnitTotal = await prisma.unitTransaction.aggregate({
            where: {
                memberId,
                isPaid: false,
                status: { not: "voided" },
                NOT: {
                    paymentMethod: "salary_cut",
                    notes: { startsWith: "Auto-generated dari penjualan kasir" },
                },
            },
            _sum: { amount: true },
            _count: { id: true },
        });

        // Count salary_cut StoreSales as unpaid piutang (filter voided in JS)
        const unpaidStoreSalesRaw = await prisma.storeSale.findMany({
            where: { memberId, paymentMethod: "salary_cut" },
            select: { totalAmount: true, metadata: true },
        });
        const unpaidStoreSales = unpaidStoreSalesRaw.filter(s => !(s.metadata?.isVoided === true));
        const unpaidStoreAmount = unpaidStoreSales.reduce((sum, s) => sum + Number(s.totalAmount), 0);
        const unpaidStoreCount = unpaidStoreSales.length;

        const totalUnpaidAmount = Number(unpaidUnitTotal._sum.amount || 0) + unpaidStoreAmount;
        const totalUnpaidCount = unpaidUnitTotal._count.id + unpaidStoreCount;
        const year = new Date().getFullYear();

        // ============================================================
        // SHU — Single Source of Truth via the canonical calculator
        // ------------------------------------------------------------
        // PREVIOUSLY this endpoint recomputed SHU with a FLAT 40% expense
        // estimate (totalExpense = totalIncome * 0.4), producing a number
        // that DIVERGED from the official Laporan SHU the operator sees at
        // /laporan/shu (which runs calculateSystemSHU). Members saw an
        // inflated/wrong estimate. Now we reuse the SAME calculator the
        // operator uses and extract this member's row from memberDistribution,
        // so the portal figure equals the official figure by construction.
        // (Same thin-wrapper fix pattern as /api/mobile/reports/shu-calculator.)
        // ============================================================
        const shuResult = await calculateSystemSHU(year);
        const myShu = shuResult.memberDistribution.find((m) => m.id === memberId);

        // Reconstruct the (myShare / systemTotal) percentages the UI expects.
        // Σ loanContribution across all members === totalSystemTransactions,
        // because each member's loanContribution IS their transaction volume.
        const totalTxVolume = shuResult.memberDistribution.reduce(
            (sum, m) => sum + (m.loanContribution || 0),
            0,
        );

        const myModal = myShu?.modalPortion ?? 0;
        const myUsaha = myShu?.usahaPortion ?? 0;
        const myCarwashBonus = myShu?.carwashBonus ?? 0;
        const myCarwashTxCount = myShu?.carwashCount ?? 0;
        const estimatedSHUTotal = myShu?.shuAmount ?? 0;

        const mySavCont = myShu?.savingsContribution ?? 0;
        const jasaModalPercent =
            shuResult.totalSavingsCapital > 0
                ? (mySavCont / shuResult.totalSavingsCapital) * 100
                : 0;
        const jasaUsahaPercent =
            totalTxVolume > 0
                ? ((myShu?.loanContribution ?? 0) / totalTxVolume) * 100
                : 0;

        return NextResponse.json({
            data: {
                member: {
                    id: member.id,
                    memberNo: member.memberNo,
                    nrp: member.nrp,
                    name: member.name,
                    category: member.category,
                    salary: member.salary ? Number(member.salary) : null,
                    tunlesKinerja: member.tunlesKinerja ? Number(member.tunlesKinerja) : null,
                    tabunganWajib: member.tabunganWajib ? Number(member.tabunganWajib) : null,
                    phone: member.phone,
                    email: member.email,
                    address: member.address,
                    joinDate: member.joinDate,
                    status: member.status,
                    branch: member.branch,
                },
                savings: {
                    accounts: savingsAccounts.map((acc) => ({
                        id: acc.id,
                        accountNo: acc.accountNo,
                        product: acc.product,
                        balance: Number(acc.balance),
                        status: acc.status,
                        // H&U extended fields (null for non-H&U products — additive, non-breaking)
                        targetAmount: acc.targetAmount ? Number(acc.targetAmount) : null,
                        monthlyTarget: acc.monthlyTarget ? Number(acc.monthlyTarget) : null,
                        maturityDate: acc.maturityDate,
                        history: acc.transactions.map((t) => ({
                            id: t.id,
                            type: t.type,
                            amount: Number(t.amount),
                            notes: t.notes,
                            date: t.transactionDate,
                        })),
                    })),
                    totalBalance: totalSavings,
                },
                loans: {
                    list: loans.map((l) => ({
                        ...l,
                        principalAmount: Number(l.principalAmount),
                        principalPaid: Number(l.principalPaid),
                        interestPaid: Number(l.interestPaid),
                        principalOutstanding: Number(l.principalOutstanding),
                        interestOutstanding: Number(l.interestOutstanding),
                        monthlyInstallment: Number(l.monthlyInstallment),
                        tenorMonths: l.tenorMonths,
                    })),
                    activeCount: activeLoans.length,
                    totalOutstanding,
                },
                unitTransactions: {
                    recent: mergedRecent,
                    byUnit: mergedStats,
                    unpaidTotal: totalUnpaidAmount,
                    unpaidCount: totalUnpaidCount,
                },
                estimatedSHU: {
                    total: estimatedSHUTotal,
                    jasaModal: Math.round(myModal),
                    jasaUsaha: Math.round(myUsaha),
                    carwashBonus: myCarwashBonus,
                    carwashCount: myCarwashTxCount,
                    jasaModalPercent,
                    jasaUsahaPercent,
                },
            },
        });
    } catch (error) {
        console.error("GET /api/member-portal/summary error:", error);
        return NextResponse.json(
            { message: "Failed to fetch member summary" },
            { status: 500 }
        );
    }
}
