/**
 * Pure helpers untuk laporan unit (`/api/unit/[slug]/laporan`).
 * Lihat test: src/__tests__/laporan-helpers.test.ts
 */

/**
 * Apakah `UnitTransaction` ini piutang otomatis (auto-generated) yang
 * menduplikasi sebuah `StoreSale`? Harus di-exclude dari laporan unit F&B
 * agar nominal Potong Gaji tidak terhitung ganda (StoreSale + UTG piutang).
 *
 * Konsisten dengan filter riwayat (`api/unit-transactions/route.ts`) dan
 * 5 route lain (member-portal, mobile, piutang-barang) — semuanya memakai
 * notes prefix `Auto-generated`. Setiap checkout Potong Gaji (toko/sales,
 * split-bill, mobile) menulis notes dengan prefix persis ini.
 *
 * Mengapa BUKAN filter prefix transactionNo: bug 2026-06-28 — filter lama
 * hanya exclude `TK-UTG-`/`MB-UTG-`, sehingga `RS-UTG-` (Resto),
 * `CF-UTG-` (Cafe LSP), `RC-UTG-`, `CL-UTG-`, `PS-UTG-` lolos → duplikat.
 * Rule berbasis notes = single source of truth, tahan terhadap unit baru.
 *
 * Prefix-match (bukan contains) agar catatan manual yang kebetulan mengandung
 * kata "Auto-generated" di tengah tidak ikut ter-exclude.
 */
export function isAutoGeneratedPiutang(notes: string | null | undefined): boolean {
    return !!notes && notes.startsWith("Auto-generated");
}
