/**
 * Pure helpers untuk dedup piutang auto-generated (StoreSale ↔ UnitTransaction).
 * Dipakai laporan unit + 5 route lain (riwayat, member-portal, mobile, piutang-barang).
 * Lihat test: src/__tests__/laporan-helpers.test.ts
 */

/**
 * Canonical prefix notes untuk UnitTransaction piutang auto-generated.
 * Semua checkout Potong Gaji (toko/sales, split-bill, mobile) menulis notes
 * dengan prefix ini. SINGLE SOURCE OF TRUTH — dipakai predicate + semua
 * DB-level Prisma filter agar tidak terjadi drift (bug 2026-06-28: laporan
 * pakai filter prefix transactionNo sendiri yg ketinggalan unit F&B).
 */
export const AUTO_GENERATED_PIUTANG_PREFIX = "Auto-generated";

/**
 * Apakah `UnitTransaction` ini piutang otomatis (auto-generated) yang
 * menduplikasi sebuah `StoreSale`? Harus di-exclude dari surface yg merge
 * StoreSale + UnitTransaction agar nominal Potong Gaji tidak terhitung ganda.
 *
 * Prefix-match (bukan contains) agar catatan manual yang kebetulan mengandung
 * kata "Auto-generated" di tengah tidak ikut ter-exclude.
 */
export function isAutoGeneratedPiutang(notes: string | null | undefined): boolean {
    return !!notes && notes.startsWith(AUTO_GENERATED_PIUTANG_PREFIX);
}
