[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.build]
cmds = ["npx prisma generate", "npm run build"]

[start]
cmd = "cp -r public .next/standalone/public && cp -r .next/static .next/standalone/.next/static && node .next/standalone/server.js"
