import { describe, it, expect } from "vitest";
import { isAutoGeneratedPiutang, AUTO_GENERATED_PIUTANG_PREFIX } from "@/lib/laporan-helpers";

/**
 * Bug 2026-06-28: duplikasi "Potong Gaji" di LAPORAN Resto/Cafe LSP.
 * Setiap checkout Potong Gaji membuat StoreSale + UnitTransaction(saleNo-linked).
 * Laporan route dulu exclude duplikat via filter prefix transactionNo
 * (hanya `TK-UTG-` / `MB-UTG-`) → lolos `RS-UTG-`, `CF-UTG-`, `RC-UTG-`,
 * `CL-UTG-`, `PS-UTG-` → pendapatan potong gaji terhitung ganda.
 *
 * Fix: predicate `isAutoGeneratedPiutang` — single source of truth, berdasar
 * notes `Auto-generated` (konsisten dgn riwayat route + 5 route lain).
 */
describe("isAutoGeneratedPiutang — deteksi duplikat StoreSale", () => {
    it("menandai piutang dari checkout toko/sales (web POS)", () => {
        const notes = "Auto-generated dari penjualan kasir. No. Transaksi: RS-26062026-0003";
        expect(isAutoGeneratedPiutang(notes)).toBe(true);
    });

    it("menandai piutang dari checkout mobile", () => {
        const notes = "Auto-generated dari penjualan kasir mobile. No. Transaksi: CF-26062026-0002";
        expect(isAutoGeneratedPiutang(notes)).toBe(true);
    });

    it("menandai piutang dari split-bill", () => {
        const notes = "Auto-generated dari penjualan kasir. Split Bill Group: SB-XYZ. No. Transaksi: RS-26062026-0004";
        expect(isAutoGeneratedPiutang(notes)).toBe(true);
    });

    // ── Bug fix: prefix per-unit (RS/CF/RC/CL/PS) harus tertangkap, ──
    //    BUKAN hanya TK/MB seperti filter lama.
    it("TIDAK peduli prefix unit — semua variant Auto-generated tertangkap", () => {
        for (const prefix of ["TK", "RS", "RC", "CF", "CL", "PS", "MB"]) {
            const notes = `Auto-generated dari penjualan kasir. No. Transaksi: ${prefix}-01012026-0001`;
            expect(isAutoGeneratedPiutang(notes), `prefix ${prefix}`).toBe(true);
        }
    });

    // ── Manual records TIDAK boleh ikut di-exclude ─────────────────
    it("melepas catatan manual kasir (bukan auto-generated)", () => {
        expect(isAutoGeneratedPiutang("Catatan manual: anggota minta dicatat")).toBe(false);
    });

    it("melepas notes kosong/null/undefined", () => {
        expect(isAutoGeneratedPiutang("")).toBe(false);
        expect(isAutoGeneratedPiutang(null)).toBe(false);
        expect(isAutoGeneratedPiutang(undefined)).toBe(false);
    });

    it("melepas notes yang kebetulan mengandung kata 'Auto-generated' di tengah", () => {
        // Harus di-PREFIX, bukan contains — hindari false positive.
        expect(isAutoGeneratedPiutang("Koreksi atas Auto-generated sebelumnya")).toBe(false);
    });
});

describe("AUTO_GENERATED_PIUTANG_PREFIX — single source of truth", () => {
    // Kontrak: constant ini adalah canonical prefix yg DIPAKAI predicate DAN
    // semua DB-level filter (6 route). Mencegah drift seperti bug laporan.
    it("adalah prefix canonical 'Auto-generated'", () => {
        expect(AUTO_GENERATED_PIUTANG_PREFIX).toBe("Auto-generated");
    });

    it("predicate konsisten dgn constant — notes diawali constant → flagged", () => {
        expect(isAutoGeneratedPiutang(`${AUTO_GENERATED_PIUTANG_PREFIX} dari penjualan kasir`)).toBe(true);
    });

    it("predicate prefix-match (bukan contains) — constant di tengah → tidak flagged", () => {
        expect(isAutoGeneratedPiutang(`X${AUTO_GENERATED_PIUTANG_PREFIX}`)).toBe(false);
    });
});
